version: '2'

services:
  app:
    image: 'root/customer:1.0.0-SNAPSHOT'
    build:
      context: ..
    container_name: app
    depends_on:
      - db
    environment:
      - QUARKUS_DATASOURCE_DB-KIND=postgresql
      - QUARKUS_DATASOURCE_USERNAME=user
      - QUARKUS_DATASOURCE_PASSWORD=password
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/customerdb
      - QUARKUS_HIBERNATE-ORM_DATABASE_GENERATION=update
    ports:
      - 8080:8080
    networks:
      - dock-db-test

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    networks:
      - dock-db-test
networks:
  dock-db-test:
    external: true


